fix: add Semantic Release variable

diff --git a/.github/workflows/ecs_deploy.yml b/.github/workflows/ecs_deploy.yml
--- a/.github/workflows/ecs_deploy.yml
+++ b/.github/workflows/ecs_deploy.yml
@@ -35,14 +35,24 @@ jobs:
           node-version: '20'
 
       - name: Semantic Release
-        run: npx semantic-release
+        run: |
+          OUTPUT=$(npx semantic-release)
+          echo "Semantic Release Output: $OUTPUT"
+          VERSION=$(echo "$OUTPUT" | grep -oP 'Published \K[0-9]+\.[0-9]+\.[0-9]+')
+          if [[ ! -z "$VERSION" ]]; then
+            echo "SEMANTIC_VERSION=$VERSION" >> $GITHUB_ENV
+            echo "Version $VERSION identified and set as SEMANTIC_VERSION"
+          else
+            echo "Error: Version number not found"
+            exit 1
+          fi
         env:
           token: ${{ secrets.GH_ISSUEFY_ROY_TOKEN }}
 
       - name: Overwrite application.yml with submodule version
         run: |
           cp submodules/application.yml src/main/resources/application.yml
-      
+
       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
